name: deep_wetlands_conda_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.13
  - numpy
  - pandas
  - rasterio
  - pillow
  - python-dotenv
  - matplotlib
  - tqdm
  - geojson
  - geopandas
  - requests
  - torchvision
  - earthengine-api
  - wandb
  - pytorch
  - pytorch-cuda=11.7
  - ipywidgets
  - pip
  - pip:
    - eeconvert
